AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template will deploy the lambda layers template.
Parameters:
    ArtifactSourceS3:
    Type: String
    Description: Name of S3 Bucket to source Build Artifacts.

Resources:
  SBFullPyLibLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
        - python3.8
        - python3.7
      LayerName: 'full-py-lib-sb-lambdas'
      Content:
        S3Bucket: !Ref ArtifactSourceS3
        S3Key: 'lambda_layers_template/lambda_layers_template_~.zip'
      Description: 'Lambda Layer to assist with importing py libs needed for Starting Blocks Lambda functions.'